/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oopdesignexercise;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // Shape testShape = new Shape();
        // testShape.valuesToString();
        // testShape.getArea();
        // testShape.getPerimeter();
        // the above is temporary, will not be Shape, but name of subclass
        // ex) Circle testCircle = new Circle();
        // testCircle. + add methods to test
    }
}
