/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oopdesignexercise;
// import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Circle testShape = new Circle(null, false, 5);
        System.out.println("The area for the circle is:  " + testShape.area());
        System.out.println("The perimeter for the circle is: " + testShape.perimeter());
        System.out.println(testShape.valuesToString());
    }
}
